_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.9.0
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.9.0
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
action_n_levels:
    value: 1
action_threshold:
    value: 1.436405
batch_size:
    value: 256
beta:
    value: 0.001
comp_degree:
    value: 1
discount:
    value: 0.99
env:
    value: halfcheetah-medium-replay-v2
eval_episodes:
    value: 10
eval_freq:
    value: 20000
expectile:
    value: 0.9
lam:
    value: 0.0006
max_timesteps:
    value: 1e+06
method:
    value: diffusion_pos_ood_compensation
n_action_samples:
    value: 10
no_normalize:
    value: false
no_schedule:
    value: false
omega:
    value: 0.9
policy_freq:
    value: 2
seed:
    value: 0
state_n_levels:
    value: 10
state_threshold:
    value: 2.636546
target_update_freq:
    value: 2
tau:
    value: 0.005
