_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.9.0
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
                - 61
            "4": 3.9.0
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
action_n_levels:
    value: 1
batch_size:
    value: 256
beta:
    value: 0.001
discount:
    value: 0.99
env:
    value: halfcheetah-medium-replay-v2
eval_episodes:
    value: 10
eval_freq:
    value: 20000
folder:
    value: train_rl
max_timesteps:
    value: 1e+06
method:
    value: diffusion_ood_action_detection
no_normalize:
    value: false
no_schedule:
    value: false
policy_freq:
    value: 2
seed:
    value: 0
target_update_freq:
    value: 2
tau:
    value: 0.005
