_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.9.0
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.9.0
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
batch_size:
    value: 256
device:
    value: 0
env:
    value: halfcheetah-medium-v2
no_normalize:
    value: false
pretrain_epochs:
    value: 100000
seed:
    value: 0
