_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.9.0
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.9.0
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
action_n_levels:
    value: 1
batch_size:
    value: 256
device:
    value: 0
env:
    value: halfcheetah-medium-replay-v2
n_samples:
    value: 5000
no_normalize:
    value: false
ood_env:
    value: halfcheetah-medium-expert-v2
pretrain_epochs:
    value: 100000
seed:
    value: 0
sigma_data:
    value: 0.5
sigma_max:
    value: 80
sigma_min:
    value: 0.002
state_n_levels:
    value: 1
